title: AI Chip Deadlines
description: Countdowns to top Architecture/Circuit/Automation/FPGA/AI conference deadlines
author: Yi Chen

domain: "cast-deadlines"
baseurl: "/cast-deadlines"

twitter_hashtag: cast-deadlines
github_username: Chen1Yi1
github_repo: cast-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
