title: AI Chip and System Deadlines
description: Countdowns to top Architecture/Circuit/Automation/FPGA/AI conference deadlines
author: Castlab

domain: "AI-Chip-System-Deadline"
baseurl: ""

twitter_hashtag: AI-Chip-System-Deadline
github_username: CastLab-KAIST
github_repo: AI-Chip-System-Deadline

markdown: kramdown
ga_id:

include: ['_pages']
