title: Circuit, Architecture and System Conference Deadlines
description: Countdowns to top Circuit/Architecture/AI conference deadlines
author: Yi Chen

domain: "cast-deadlines.github.io"
baseurl: "/cast-deadlines.github.io"

twitter_hashtag: cast-deadlines
github_username: Chen1Yi1
github_repo: cast-deadlines.github.io

markdown: kramdown
ga_id:

include: ['_pages']
